name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t ghrc.io/kevingr19-univ/dockertd1 .

  push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Pushes the Docker image to GHRC
      run: docker push ghrc.io/kevingr19-univ/dockertd1
